import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
      {
        name: 'Jim',
        email: 'jim@admin.com',
        password: hashSync('123Ox', 10),
        role: 'admin',
      },
      {
        name: 'Abu',
        email: 'abu@admin.com',
        password: hashSync('123456', 10),
        role: 'admin',
      },
  ],
  products: [
    {
      name: 'Daggers Ringer Tee',
      slug: 'daggers-ringer-tee',
      category: "Tees",
      description: 'Heavyweight cotton fabric (Peach)',
      images: [
        '/images/sample-products/2of1.jpeg',
        '/images/sample-products/2of2.jpeg',
      ],
      price: 28000.00,
      rating: 4.5,
      numReviews: 0,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.png',
    },
    {
      name: 'Daggers Trackpant',
      slug: 'daggers-trackpant-white',
      category: "Pants",
      description: 'Heavyweight lycra fabric (White with blue stripes)',
      images: [
        '/images/sample-products/8of1.jpeg',
        '/images/sample-products/8of2.jpeg',
      ],
      price: 35000.00,
      rating: 4.9,
      numReviews: 0,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Trackpant',
      slug: 'daggers-trackpant-cream',
      category: "Pants",
      description: 'Heavyweight lycra fabric (Cream with brown stripes)',
      images: [
        '/images/sample-products/4of1.jpeg',
        '/images/sample-products/4of2.jpeg',
      ],
      price: 35000.00,
      rating: 4.9,
      numReviews: 0,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Flapped Hat',
      slug: 'daggers-flapped-hat',
      category: "Hats",
      description: 'Iconic fabric hat with cotton twill',
      images: [
        '/images/sample-products/6of1.jpeg',
        '/images/sample-products/6of2.jpeg',
      ],
      price: 40000.00,
      rating: 4.7,
      numReviews: 0,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Hoodie',
      slug: 'daggers-hoodie-brown',
      category: "Hoodies",
      description: 'Heavyweight cotton (Brown)',
      images: [
        '/images/sample-products/3of1.jpeg',
        '/images/sample-products/3of2.jpeg',
      ],
      price: 35000.00,
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-1.png',
    },
    {
      name: 'Daggers Hoodie',
      slug: 'daggers-hoodie-blue',
      category: "Hoodies",
      description: 'Heavyweight cotton (Blue)',
      images: [
        '/images/sample-products/7of1.jpeg',
        '/images/sample-products/7of2.jpeg',
      ],
      price: 35000.00,
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Knit Sweater',
      slug: 'daggers-knit-sweater',
      category: "Sweatshirts",
      description: 'Heavyweight knit fabric',
      images: [
        '/images/sample-products/5of1.jpeg',
        '/images/sample-products/5of2.jpeg',
      ],
      price: 40000.00,
      rating: 4.6,
      numReviews: 0,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Logo Tee',
      slug: 'daggers-logo-tee',
      category: "Tees",
      description: 'Heavyweight cotton fabric (Cream)',
      images: [
        '/images/sample-products/1of1.jpeg',
        '/images/sample-products/1of2.jpeg',
      ],
      price: 28000.00,
      rating: 4.2,
      numReviews: 1,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Leopard Scarf',
      slug: 'daggers-leopard-scarf',
      category: "Accessories",
      description: 'Leopard print scarf with Daggers monogram border',
      images: [
        '/images/sample-products/9of1.jpeg',
        '/images/sample-products/9of2.jpeg',
      ],
      price: 12000.00,
      rating: 4.8,
      numReviews: 0,
      stock: 20,
      isFeatured: true,
      banner: '/images/promo2.png',
    },
  ],
};

export default sampleData;
