import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
      {
        name: 'Jim',
        email: 'jim@example.com',
        password: hashSync('123456', 10),
        role: 'admin',
      },
  ],
  products: [
    {
      name: 'Daggers Ringer Tee',
      slug: 'daggers-ringer-tee',
      category: "Tees",
      description: 'Heavyweight cotton fabric (Peach)',
      images: [
        '/images/sample-products/2of1.jpeg',
        '/images/sample-products/2of2.jpeg',
      ],
      price: 59.99,
      rating: 4.5,
      numReviews: 10,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.png',
    },
    {
      name: 'Daggers Logo Tee',
      slug: 'daggers-logo-tee',
      category: "Tees",
      description: 'Heavyweight cotton fabric (Cream)',
      images: [
        '/images/sample-products/1of1.jpeg',
        '/images/sample-products/2of2.jpeg',
      ],
      price: 85.9,
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Trackpant',
      slug: 'daggers-trackpant',
      category: "Pants",
      description: 'Heavyweight lycra fabric (Cream)',
      images: [
        '/images/sample-products/4of1.jpeg',
        '/images/sample-products/4of2.jpeg',
      ],
      price: 99.95,
      rating: 4.9,
      numReviews: 3,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Hoodie',
      slug: 'daggers-hoodie',
      category: "Hoodies",
      description: 'Heavyweight cotton',
      images: [
        '/images/sample-products/3of1.jpeg',
        '/images/sample-products/3of2.jpeg',
      ],
      price: 39.95,
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: true,
      banner: 'banner-1.png',
    },
    {
      name: 'Daggers Flapped Hat',
      slug: 'daggers-flapped-hat',
      category: "Hats",
      description: 'Iconic fabric hat with cotton twill',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 79.99,
      rating: 4.7,
      numReviews: 18,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Daggers Knit Sweater',
      slug: 'daggers-knit-sweater',
      category: "Men's Sweatshirts",
      description: 'Heavyweight knit fabric',
      images: [
        '/images/sample-products/5of1.jpeg',
        '/images/sample-products/5of2.jpeg',
      ],
      price: 99.99,
      rating: 4.6,
      numReviews: 12,
      stock: 0,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
